name = "podiverzum-bot-prerender"
main = "worker.js"
compatibility_date = "2025-01-01"

routes = [
  { pattern = "podiverzum.com/*", zone_name = "podiverzum.com" },
  { pattern = "www.podiverzum.com/*", zone_name = "podiverzum.com" },
]
